name: Docker Image build and push

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        required: true
        type: string

      version:
        required: true
        type: number




jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ inputs.name}}:${{ inputs.version }}

    - name: Login to Docker Hub
      run: docker login -u arkyy21 -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Image push
      run: docker image push ${{ inputs.name}}:${{ inputs.version }}

